# Generated by Django 4.2.2 on 2023-06-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion_parejas', '0002_parejas_numero_pareja'),
    ]

    operations = [
        migrations.AddField(
            model_name='parejas',
            name='Nombre_pareja',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
